version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: e2etester
      POSTGRES_PASSWORD: notastupidpassword
      POSTGRES_DB: e2etestdatabase
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DB_CONN_STR: postgres://e2etester:notastupidpassword@db:5432/e2etestdatabase?sslmode=disable
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "go run scripts/wait-for-db.go && goose -dir migrations postgres \"$${DB_CONN_STR}\" up && go run main.go"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8080