services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONN_STR=postgres://postgres:notastupidpassword@db:5432/my_local_db?sslmode=disable
    command: sh -c "goose -dir migrations postgres \"$${DB_CONN_STR}\" up && go run main.go"

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notastupidpassword
      POSTGRES_DB: my_local_db
    tmpfs:
      - /var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8080
  tests:
    build:
      context: .
    depends_on:
      - backend
      - frontend
    environment:
      - BASE_URL=http://frontend:3000
    command: npm test