services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "8080:8080"
    environment:
      - ENV=docker
      - PORT=8080
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

  tests:
    image: mcr.microsoft.com/playwright:v1.44.0-jammy
    container_name: e2e_tests
    depends_on:
      - frontend
    working_dir: /tests
    volumes:
      - ./frontend:/tests
    command: >
      sh -c "
        echo 'Waiting for frontend...';
        until curl -s http://frontend:5173; do sleep 1; done;
        echo 'Frontend is up! Running Playwright tests...';
        npx playwright install --with-deps &&
        npx playwright test
      "

volumes:
  db_data:
